### PR TITLE
Fix error build apk

### PR DESCRIPTION
**Pull request by DevJoaoLopes**
Switch version sdk in `build.gradle`

### CODE REVIEW

**Comment by DevJoaoLopes** [comment]
Close #19

**Comment by DevJoaoLopes** [comment]
@aloisdeniel ??

**Comment by kleysonr** [comment]
@aloisdeniel May you release a new version with this fix, please ?

**Comment by shubham26S** [comment]
@DevJoaoLopes @aloisdeniel is this issue fixed? Any set of steps to follow on my end?
The plugin on the pub.dev is old and may not have the fix.

**Pull request merged**
